default_settings: null
behaviors:
  BombermanAgent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 128
      learning_rate: 0.0003
      beta: 5.0e-3
      epsilon: 0.2
      lambd:  0.95
      num_epoch: 3
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2
      reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0        
    max_steps: 100000
    time_horizon: 100
    summary_freq: 1000
    