behaviors:
  BombermanAgentFullV2SAC:
    trainer_type: sac
    hyperparameters:
      buffer_size: 50000
      learning_rate: 3.0e-4
      batch_size: 64
      tau: 0.005
      reward_signal_steps_per_update: 1
      steps_per_update: 10
    network_settings:
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 50000000
    time_horizon: 64
    summary_freq: 10000
